### ISSUE TITLE
Designate central repo (maybe .github?) for all assets, group info, sub-group info etc. and move the data there

### ISSUE THREAD

**Issue by PatrickHeneise** [cyprus-developer-community/home#1]

**Comment by MarioSimou** [comment]
Just for clarity, is the repo intended to used as a central location to store data for *all repositories under the cdc org**? If that's the case, we need determine a structure we want to follow in order to separate concerns. A naive suggestion would be: 
```
[repositories]
   [repository A]
      [any data used within repository A]
   ...
   [repository N]
      [any data used within repository N]  
```

**Comment by PatrickHeneise** [comment]
If we'd store all our assets in `home` or `.github`, we could use raw file links to access them from anywhere. the main idea is to avoid duplication and always have "one source of truth", like the new pydata logo we just got today, needs to be displayed on the homepage and GitHub readme as well.

**Comment by PatrickHeneise** [comment]
After thinking about it for a bit, I think this repo (`home`) is the best place to store all the info. We can create a file `groups.json` with all the information.

**Comment by MarioSimou** [comment]
Okay, that makes sense. Do we need to agree on a way to organise those assets/files? I believe there is a lot of information that can go there and we may need to agree how we should organise them. The downside is that it may be premature because we don't really know what information will be pushed there

**Comment by PatrickHeneise** [comment]
Started a new file here: https://github.com/cyprus-developer-community/home/blob/main/groups.json

We'll add stuff along the way.
